services:
  # backend:
  #   build: ./backend
  #   security_opt:
  #     - seccomp:unconfined
  #   container_name: point_vis_backend
  #   ports:
  #     - 8000:8000
  #   volumes:
  #     - ./backend:/app

  nginx:
    build: ./
    ports:
      - 8080:80
      - 8081:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/usr/share/nginx/html
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - matomo:/var/www/html/matomo

  certbot:
    image: certbot/certbot
    volumes:
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email wwydmanski@gmail.com --agree-tos --no-eff-email -d protein.mcb.bio -d protein-structure-landscape.sano.science

volumes:
  web-root:
  certbot-etc:
  certbot-var:
  db:
  matomo: